### ISSUE TITLE
When fs-watcher is not available, exception should point to the installation page

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest-plugin-watch#6]

**Comment by owenvoke** [comment]
Do you think it's ok to just have something like this? Or do you want it to be used as the output? 🙂

![image](https://user-images.githubusercontent.com/1899334/85876551-cb95eb00-b7cd-11ea-8ab0-f41a6413607d.png)

![image](https://user-images.githubusercontent.com/1899334/85877468-1d8b4080-b7cf-11ea-9cce-3c9334338050.png)

**Comment by nunomaduro** [comment]
The second option. And the title should be something like this: https://github.com/pestphp/pest-plugin-coverage/blob/53d6300cb52042077c33209a66206160f645aa8e/src/Plugin.php#L99.

**Comment by nunomaduro** [comment]
Make sure you give an line between the `pest --watch` and the error.
